kind: Service
apiVersion: v1

metadata:
  name: nginx-nodes
  namespace: default
spec:
  clusterIP: None
  selector:
    app: nginx
  ports:
    - name: http
      port: 80

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

#kubectl run bash --rm -it --image ubuntu -- bash 